In [1]:
import tensorflow as tf

In [2]:
#create tensor
x=tf.random.normal(shape=(2,5),mean=0,stddev=1)
print(x)
x.shape




tf.Tensor(
[[-1.2908385   0.09420709 -0.07000785 -1.6368151  -1.083136  ]
 [ 0.41910577  0.34770674  0.87899256  0.16626717  0.4915189 ]], shape=(2, 5), dtype=float32)


TensorShape([2, 5])

In [3]:
x=tf.zeros(shape=(2,5))
print(x)
x=tf.ones(shape=(2,5))
print(x)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(2, 5), dtype=float32)


In [6]:
c=tf.Variable(x)
c[0,0].assign(10)
print(c)

<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
array([[10.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)>


In [8]:
x=tf.Variable(tf.random.normal(shape=(5,4)))
print(x)

<tf.Variable 'Variable:0' shape=(5, 4) dtype=float32, numpy=
array([[ 0.8495761 ,  1.3187491 ,  1.834096  , -0.5939701 ],
       [ 0.06657314, -1.4044238 ,  0.25165504, -1.01449   ],
       [ 0.5790624 ,  0.94896495,  1.1633441 , -0.18566069],
       [-2.0826256 , -0.6721943 , -0.65947104, -0.69996303],
       [-0.34603807,  0.06467296,  0.00417533,  0.1736899 ]],
      dtype=float32)>


In [9]:
print(tf.matmul(c,x))
print(tf.square(x))

tf.Tensor(
[[ 6.7127333  12.124511   19.100662   -7.6661253 ]
 [-0.9334521   0.25576878  2.5937996  -2.320394  ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[7.2177958e-01 1.7390991e+00 3.3639081e+00 3.5280052e-01]
 [4.4319835e-03 1.9724063e+00 6.3330263e-02 1.0291899e+00]
 [3.3531326e-01 9.0053451e-01 1.3533696e+00 3.4469891e-02]
 [4.3373294e+00 4.5184517e-01 4.3490204e-01 4.8994824e-01]
 [1.1974235e-01 4.1825920e-03 1.7433382e-05 3.0168181e-02]], shape=(5, 4), dtype=float32)


In [11]:
y=x+1
print(x*y)

tf.Tensor(
[[ 1.57135570e+00  3.05784798e+00  5.19800377e+00 -2.41169617e-01]
 [ 7.10051283e-02  5.67982495e-01  3.14985305e-01  1.46999685e-02]
 [ 9.14375722e-01  1.84949946e+00  2.51671386e+00 -1.51190788e-01]
 [ 2.25470376e+00 -2.20349118e-01 -2.24568993e-01 -2.10014790e-01]
 [-2.26295710e-01  6.88555539e-02  4.19276347e-03  2.03858078e-01]], shape=(5, 4), dtype=float32)


In [13]:
def f(x):
    return 2*tf.math.log(x)+3
print(f(x))

with tf.GradientTape() as tape:
    y=f(x)
    dy_dx=tape.gradient(y,x)
print(dy_dx)

tf.Tensor(
[[ 2.6739645   3.5533671   4.2131033          nan]
 [-2.418908           nan  0.24060798         nan]
 [ 1.9073099   2.8952332   3.3025975          nan]
 [        nan         nan         nan         nan]
 [        nan -2.4768243  -7.9571238  -0.5009675 ]], shape=(5, 4), dtype=float32)
tf.Tensor(
[[  2.354115     1.5165888    1.0904555   -3.3671727 ]
 [ 30.042145    -1.4240716    7.9473867   -1.9714339 ]
 [  3.4538589    2.1075594    1.7191817  -10.77234   ]
 [ -0.96032625  -2.9753304   -3.0327334   -2.8572938 ]
 [ -5.779711    30.924824   479.00406     11.514774  ]], shape=(5, 4), dtype=float32)
